# This workflow installs dependencies and builds the source code.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    paths: 
      - '**.js'
      - '**.ts'
      - '**.html'
      - './assets/**'
  pull_request:
    branches: [ main ]
    paths: 
      - '**.js'
      - '**.ts'
      - '**.html'
      - './assets/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: corepack enable
    - run: yarn install --frozen-lockfile
    - run: yarn build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        #name: # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: './dist/'
        # The desired behavior if no files are found using the provided path.
